//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLL.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee after add not found!.
        /// </summary>
        internal static string AfterAddEmployeeNotFound {
            get {
                return ResourceManager.GetString("AfterAddEmployeeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After add position not found.
        /// </summary>
        internal static string AfterAddPositionNotFound {
            get {
                return ResourceManager.GetString("AfterAddPositionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role after add not found!.
        /// </summary>
        internal static string AfterAddRoleNotFound {
            get {
                return ResourceManager.GetString("AfterAddRoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User after add not found!.
        /// </summary>
        internal static string AfterAddUserNotFound {
            get {
                return ResourceManager.GetString("AfterAddUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fewer columns than necessary for data model.
        /// </summary>
        internal static string ColCountSmallerThanDataModels {
            get {
                return ResourceManager.GetString("ColCountSmallerThanDataModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder for content not found..
        /// </summary>
        internal static string ContentPathNotFound {
            get {
                return ResourceManager.GetString("ContentPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count items must be at least 1..
        /// </summary>
        internal static string CountItemsLeastOne {
            get {
                return ResourceManager.GetString("CountItemsLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сreating a user with current role is prohibited!.
        /// </summary>
        internal static string CreatingWithRoleIsProhibited {
            get {
                return ResourceManager.GetString("CreatingWithRoleIsProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data for item is not valid!.
        /// </summary>
        internal static string DataIsNotValid {
            get {
                return ResourceManager.GetString("DataIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has not been deleted from the database!.
        /// </summary>
        internal static string DataNotDeletedFromDB {
            get {
                return ResourceManager.GetString("DataNotDeletedFromDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has not been updated in the database!.
        /// </summary>
        internal static string DataNotUpdatedInDB {
            get {
                return ResourceManager.GetString("DataNotUpdatedInDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data was not written to the database!.
        /// </summary>
        internal static string DataNotWrittenToDB {
            get {
                return ResourceManager.GetString("DataNotWrittenToDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of issue.
        /// </summary>
        internal static string DateOfIssue {
            get {
                return ResourceManager.GetString("DateOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver categories (category) not found.
        /// </summary>
        internal static string DriverCategoriesNotFound {
            get {
                return ResourceManager.GetString("DriverCategoriesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver category already exist in database!.
        /// </summary>
        internal static string DriverCategoryAlreadyExist {
            get {
                return ResourceManager.GetString("DriverCategoryAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver category not found!.
        /// </summary>
        internal static string DriverCategoryNotFound {
            get {
                return ResourceManager.GetString("DriverCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver license.
        /// </summary>
        internal static string DriverLicense {
            get {
                return ResourceManager.GetString("DriverLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver license already exist in database!.
        /// </summary>
        internal static string DriverLicenseAlreadyExist {
            get {
                return ResourceManager.GetString("DriverLicenseAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver license not found!.
        /// </summary>
        internal static string DriverLicenseNotFound {
            get {
                return ResourceManager.GetString("DriverLicenseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver license photo already exist in database!.
        /// </summary>
        internal static string DriverLicensePhotoAlreadyExist {
            get {
                return ResourceManager.GetString("DriverLicensePhotoAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver license photo not found!.
        /// </summary>
        internal static string DriverLicensePhotoNotFound {
            get {
                return ResourceManager.GetString("DriverLicensePhotoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver license photos.
        /// </summary>
        internal static string DriverLicensePhotos {
            get {
                return ResourceManager.GetString("DriverLicensePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver license photos not found!.
        /// </summary>
        internal static string DriverLicensePhotosNotFound {
            get {
                return ResourceManager.GetString("DriverLicensePhotosNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver licenses not found!.
        /// </summary>
        internal static string DriverLicensesNotFound {
            get {
                return ResourceManager.GetString("DriverLicensesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver medical certificate.
        /// </summary>
        internal static string DriverMedicalCertificate {
            get {
                return ResourceManager.GetString("DriverMedicalCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver medical certificate exist in database!.
        /// </summary>
        internal static string DriverMedicalCertificateAlreadyExist {
            get {
                return ResourceManager.GetString("DriverMedicalCertificateAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver medical certificate not found!.
        /// </summary>
        internal static string DriverMedicalCertificateNotFound {
            get {
                return ResourceManager.GetString("DriverMedicalCertificateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver medical certificate photo already exist in database!.
        /// </summary>
        internal static string DriverMedicalCertificatePhotoAlreadyExist {
            get {
                return ResourceManager.GetString("DriverMedicalCertificatePhotoAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver medical certificate photo not found!.
        /// </summary>
        internal static string DriverMedicalCertificatePhotoNotFound {
            get {
                return ResourceManager.GetString("DriverMedicalCertificatePhotoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver medical certificate photos.
        /// </summary>
        internal static string DriverMedicalCertificatePhotos {
            get {
                return ResourceManager.GetString("DriverMedicalCertificatePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver medical certificates photo not found!.
        /// </summary>
        internal static string DriverMedicalCertificatePhotosNotFound {
            get {
                return ResourceManager.GetString("DriverMedicalCertificatePhotosNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver medical certificates not found!.
        /// </summary>
        internal static string DriverMedicalCertificatesNotFound {
            get {
                return ResourceManager.GetString("DriverMedicalCertificatesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee already exist in database!.
        /// </summary>
        internal static string EmployeeAlreadyExist {
            get {
                return ResourceManager.GetString("EmployeeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete employee from database.
        /// </summary>
        internal static string EmployeeFoundAfterDelete {
            get {
                return ResourceManager.GetString("EmployeeFoundAfterDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee not found!.
        /// </summary>
        internal static string EmployeeNotFound {
            get {
                return ResourceManager.GetString("EmployeeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees not found!.
        /// </summary>
        internal static string EmployeesNotFound {
            get {
                return ResourceManager.GetString("EmployeesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter date of issue.
        /// </summary>
        internal static string EnterDateOfIssue {
            get {
                return ResourceManager.GetString("EnterDateOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load driver license photos.
        /// </summary>
        internal static string EnterDriverLicensePhotos {
            get {
                return ResourceManager.GetString("EnterDriverLicensePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load driver medical certificate photos.
        /// </summary>
        internal static string EnterDriverMedicalCertificatePhotos {
            get {
                return ResourceManager.GetString("EnterDriverMedicalCertificatePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter expiry date.
        /// </summary>
        internal static string EnterExpiryDate {
            get {
                return ResourceManager.GetString("EnterExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter firstname.
        /// </summary>
        internal static string EnterFirstName {
            get {
                return ResourceManager.GetString("EnterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter patronymic.
        /// </summary>
        internal static string EnterPatronymic {
            get {
                return ResourceManager.GetString("EnterPatronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter position.
        /// </summary>
        internal static string EnterPosition {
            get {
                return ResourceManager.GetString("EnterPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter serial number.
        /// </summary>
        internal static string EnterSerialNumber {
            get {
                return ResourceManager.GetString("EnterSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter surname.
        /// </summary>
        internal static string EnterSurname {
            get {
                return ResourceManager.GetString("EnterSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry date.
        /// </summary>
        internal static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded file not a picture!.
        /// </summary>
        internal static string FileNotPicture {
            get {
                return ResourceManager.GetString("FileNotPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded file not a Excel!.
        /// </summary>
        internal static string FileNotXLWorkbook {
            get {
                return ResourceManager.GetString("FileNotXLWorkbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found! Invalid login and / or password intered..
        /// </summary>
        internal static string InvalidLoginAndOrPassword {
            get {
                return ResourceManager.GetString("InvalidLoginAndOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role not found! Invalid role name intered..
        /// </summary>
        internal static string InvalidRoleName {
            get {
                return ResourceManager.GetString("InvalidRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with current login already exists!.
        /// </summary>
        internal static string LoginAlreadyExists {
            get {
                return ResourceManager.GetString("LoginAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data for item!.
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No photo.
        /// </summary>
        internal static string NoPhoto {
            get {
                return ResourceManager.GetString("NoPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open driver categories.
        /// </summary>
        internal static string OpenCategories {
            get {
                return ResourceManager.GetString("OpenCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patronymic.
        /// </summary>
        internal static string Patronymic {
            get {
                return ResourceManager.GetString("Patronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo file already exist..
        /// </summary>
        internal static string PhotoFileAlreadyExist {
            get {
                return ResourceManager.GetString("PhotoFileAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo file not found in folder. Name of photo file: .
        /// </summary>
        internal static string PhotoFileWithIdNotFound {
            get {
                return ResourceManager.GetString("PhotoFileWithIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position already exist in database!.
        /// </summary>
        internal static string PositionAlreadyExist {
            get {
                return ResourceManager.GetString("PositionAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete position from database.
        /// </summary>
        internal static string PositionFoundAfterDelete {
            get {
                return ResourceManager.GetString("PositionFoundAfterDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position not found!.
        /// </summary>
        internal static string PositionNotFound {
            get {
                return ResourceManager.GetString("PositionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions not found!.
        /// </summary>
        internal static string PositionsNotFound {
            get {
                return ResourceManager.GetString("PositionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record you attempted to edit was modified by another user after you got the original value. The edit operation was canceled and the current values in the database have been displayed. If you still want to edit this record, try begin again..
        /// </summary>
        internal static string RecordToEditWasModifiedAnotherUser {
            get {
                return ResourceManager.GetString("RecordToEditWasModifiedAnotherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role with current name already exists!.
        /// </summary>
        internal static string RoleAlreadyExists {
            get {
                return ResourceManager.GetString("RoleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role with current name not found! Perhaps such a role does not exist..
        /// </summary>
        internal static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row count one or less.
        /// </summary>
        internal static string RowCountOneOrLess {
            get {
                return ResourceManager.GetString("RowCountOneOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number.
        /// </summary>
        internal static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current start item does not exist..
        /// </summary>
        internal static string StartItemNotExist {
            get {
                return ResourceManager.GetString("StartItemNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firstname must begin with a capital letter and be no more than 30 characters..
        /// </summary>
        internal static string ValidateFirstName {
            get {
                return ResourceManager.GetString("ValidateFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patronymic must begin with a capital letter and be no more than 30 characters..
        /// </summary>
        internal static string ValidatePatronymic {
            get {
                return ResourceManager.GetString("ValidatePatronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The position must begin with a capital letter and be no more than 30 characters..
        /// </summary>
        internal static string ValidatePosition {
            get {
                return ResourceManager.GetString("ValidatePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The surname must begin with a capital letter and be no more than 30 characters..
        /// </summary>
        internal static string ValidateSurname {
            get {
                return ResourceManager.GetString("ValidateSurname", resourceCulture);
            }
        }
    }
}
